# Generated by Django 3.2.16 on 2023-01-04 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230104_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cb6a41-4a37-462d-9ca9-fcedf821e1e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='colorvarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cb6a41-4a37-462d-9ca9-fcedf821e1e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cb6a41-4a37-462d-9ca9-fcedf821e1e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cb6a41-4a37-462d-9ca9-fcedf821e1e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97cb6a41-4a37-462d-9ca9-fcedf821e1e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
