# Generated by Django 3.2.16 on 2023-01-06 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230106_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='colorvarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f3752e-a6a2-4298-8f14-51cb7ceced99'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
