# Generated by Django 3.2.16 on 2023-01-10 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230108_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='colorvarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad4b4b1-0561-4148-b4da-c8e6f7922f84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
