# Generated by Django 3.2.16 on 2023-01-10 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20230110_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='colorvarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f507cef6-d5ba-4c0a-9538-1c062d8c0a62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
