# Generated by Django 3.2.16 on 2023-01-11 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230111_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='colorvarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('449c7b77-c82f-4bae-b2f6-8a6f35baa17e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
